services:
  product-db:
    image: postgres:17.5-alpine
    container_name: product-db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"  # Host:Container
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge
